# Generated by Django 5.1.1 on 2024-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothestype",
            name="key",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userclothes",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
