# Generated by Django 5.1.1 on 2024-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailotp_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="is verified"),
        ),
    ]
