# Generated by Django 5.1.1 on 2024-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_region_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_group",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="age group"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="body_shape",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="body shape"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="clothing_size",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="clothing size"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_styles",
            field=models.JSONField(
                blank=True, null=True, verbose_name="current styles"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="height"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skin_color",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="skin color"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="weight"
            ),
        ),
    ]
